[project]
name = "fig-jam"
version = "0.1.0"
description = "Agnostic fonfig manager"
readme = "README.md"
authors = [
    { name = "Martin Hanicinec", email = "hanicinecm@gmail.com" }
]
requires-python = ">=3.8"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipython",
    "pydantic",
    "pytest-cov",
    "pyyaml",
    "ruff",
    "syrupy",
]

[[tool.uv.index]]
name = "test-pypi"
url = "https://test.pypi.org/simple"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
